remote_theme: just-the-docs/just-the-docs
color_scheme: dark
enable_darkmode_toggle: true
title: Silicon Zen
description: Modern Koans for the AI Age
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions:
    - autolink
    - footnotes
    - smart
plugins:
  - jekyll-relative-links
defaults:
  - scope:
      path: "koans"
      type: "pages"
    values:
      layout: "default"
relative_links:
  enabled: true
  collections: true
